steps:
  - uses: actions/checkout@v4
  - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
    # Version is set implicitly with .ruby-version
  - run: bundle install
  - run: bundle exec rake test
